from __future__ import annotations

from typing import Any, Protocol


class AuthProvider(Protocol):
    async def start_login(self) -> dict[str, Any]: ...
    async def poll_login(self) -> dict[str, Any]: ...
    def session_status(self) -> dict[str, Any]: ...
    async def restore(self) -> None: ...
    async def refresh(self) -> dict[str, Any]: ...
    async def logout(self) -> None: ...
