import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import App from './App'
const config={xhs:{configured:false,cookie_saved:false,cookie_length:0,username_saved:false,username_masked:'',check:{status:'unknown',message:'尚未检测'}},notion:{configured:true,token_saved:true,token_length:12,database_id:'db',check:{status:'configured',message:'成功',database_name:'知识库',database_url:'https://notion.so/db'}}}
const idle={task_id:null,status:'idle',current_url:'',processed:0,success:0,skipped_duplicate:0,failed:0,last_error:''}
let taskStatus:any=idle;let requests:Array<{url:string,options:RequestInit}>=[]
const inbox={version:'v',raw_content:'https://example.com',pending_url_count:1,items:[{item_id:'i',content:'https://example.com',urls:['https://example.com'],status:'pending',failure_reason:''}]}
const response=(data:any)=>Promise.resolve(new Response(JSON.stringify({success:true,message:'ok',data}),{status:200,headers:{'Content-Type':'application/json'}}))
beforeEach(()=>{taskStatus=idle;requests=[];vi.stubGlobal('confirm',vi.fn(()=>true));vi.stubGlobal('fetch',vi.fn((input:RequestInfo|URL,options:RequestInit={})=>{const url=String(input);requests.push({url,options});if(url==='/api/config/status')return response(config);if(url==='/api/xiaohongshu/test')return Promise.resolve(new Response(JSON.stringify({success:false,message:'登录成功，但没有读取到收藏页：收藏入口不可见',data:{status:'favorites_unavailable',message:'登录成功，但没有读取到收藏页：收藏入口不可见',sample_count:0}}),{status:200,headers:{'Content-Type':'application/json'}}));if(url==='/api/inbox/items'&&options.method==='DELETE')return response({...inbox,version:'v2',raw_content:'',pending_url_count:0,items:[]});if(url==='/api/inbox')return response(inbox);if(url==='/api/processor/start'){taskStatus={...idle,task_id:'t',status:'processing'};setTimeout(()=>taskStatus={...taskStatus,status:'success',processed:1,success:1},50);return response(taskStatus)}if(url==='/api/processor/status')return response(taskStatus);if(url==='/api/notion/recent')return response({items:[{item_id:'1',title:'文章',original_url:'https://source',normalized_url:'https://source/',notion_url:'https://notion/page',created_at:'2026-01-01T00:00:00Z',status:'archived'}]});if(url==='/api/hot')return response({content:'# 项目记忆\n\n<script>bad()</script>'});if(url==='/api/config/xhs')return response(config.xhs);return response({})}))})
afterEach(()=>{cleanup();vi.unstubAllGlobals()})
describe('Knowledge Console',()=>{
it('renders every region and safe markdown',async()=>{render(<App/>);expect(await screen.findByRole('heading',{name:/Knowledge Console/})).toBeInTheDocument();for(const title of ['小红书登录配置','Notion 数据库配置','待整理收件箱','自动整理任务','最近 Notion 整理结果','hot.md 项目记忆'])expect(screen.getByText(title)).toBeInTheDocument();expect(await screen.findByText('文章')).toBeInTheDocument();expect(document.querySelector('script')).toBeNull()})
it('clears a saved secret',async()=>{const user=userEvent.setup();render(<App/>);const field=await screen.findByLabelText('Cookie');await user.type(field,'private-cookie');await user.click(screen.getByRole('button',{name:'保存小红书配置'}));await waitFor(()=>expect(field).toHaveValue(''));expect(requests.find(x=>x.url==='/api/config/xhs'&&x.options.method==='POST')?.options.body).toContain('private-cookie');expect(screen.queryByDisplayValue('private-cookie')).toBeNull()})
it('starts and polls a background job',async()=>{render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'开始整理'}));await waitFor(()=>expect(requests.some(x=>x.url==='/api/processor/start')).toBe(true));await waitFor(()=>expect(screen.getAllByText('成功').some(node=>node.classList.contains('badge'))).toBe(true),{timeout:2500})})
it('selects all inbox items and deletes them in one request',async()=>{const user=userEvent.setup();render(<App/>);await user.click(await screen.findByRole('button',{name:'全选'}));expect(screen.getByText('已选择 1 条')).toBeInTheDocument();expect(screen.getByRole('checkbox')).toBeChecked();await user.click(screen.getByRole('button',{name:'删除选中'}));await waitFor(()=>expect(requests.some(x=>x.url==='/api/inbox/items'&&x.options.method==='DELETE')).toBe(true));const request=requests.find(x=>x.url==='/api/inbox/items'&&x.options.method==='DELETE');expect(JSON.parse(String(request?.options.body))).toEqual({item_ids:['i'],version:'v'});expect(await screen.findByText('队列为空')).toBeInTheDocument()})
it('shows that login succeeded when favorites cannot be read',async()=>{const user=userEvent.setup();render(<App/>);await user.click(await screen.findByRole('button',{name:'测试登录'}));expect(await screen.findByText('登录成功，但没有读取到收藏页：收藏入口不可见')).toBeInTheDocument()})
})
