import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import App from './App'
const config={notion:{configured:true,token_saved:true,token_length:12,database_id:'db',check:{status:'configured',message:'成功',database_name:'知识库',database_url:'https://notion.so/db'}}}
const session={status:'idle',loggedIn:false,cookieValid:false,account:{id:'',nickname:'',avatarUrl:''},loginTime:null,updatedAt:'2026-01-01T00:00:00Z',expireAt:null,remainingSeconds:null}
const idle={task_id:null,status:'idle',current_url:'',processed:0,success:0,skipped_duplicate:0,failed:0,last_error:''}
let taskStatus:any=idle;let requests:Array<{url:string,options:RequestInit}>=[]
let xhsTask:any={task_id:null,status:'idle',phase:'idle',message:'等待开始',requested:0,fetched:0,processed:0,success:0,failed:0,current_index:0,current_title:'',last_error:'',started_at:null,updated_at:null,finished_at:null}
const inbox={version:'v',raw_content:'https://example.com',pending_item_count:1,pending_url_count:1,items:[{item_id:'i',content:'https://example.com',urls:['https://example.com'],status:'pending',failure_reason:''}]}
let inboxData=inbox
const response=(data:any)=>Promise.resolve(new Response(JSON.stringify({success:true,message:'ok',data}),{status:200,headers:{'Content-Type':'application/json'}}))
beforeEach(()=>{taskStatus=idle;xhsTask={task_id:null,status:'idle',phase:'idle',step:'idle',message:'等待开始',requested:0,fetched:0,discovered:0,processed:0,success:0,failed:0,current_index:0,current_title:'',page_url:'',last_error:'',started_at:null,updated_at:null,last_progress_at:null,heartbeat_at:null,finished_at:null};inboxData=inbox;requests=[];vi.stubGlobal('confirm',vi.fn(()=>true));vi.stubGlobal('fetch',vi.fn((input:RequestInfo|URL,options:RequestInit={})=>{const url=String(input);requests.push({url,options});if(url==='/api/config/status')return response(config);if(url==='/api/xhs/session')return response(session);if(url==='/api/xhs/sync'&&options.method==='POST'){const now=new Date().toISOString();xhsTask={...xhsTask,task_id:'xhs-task',status:'fetching',phase:'fetching',step:'opening_favorites',message:'正在打开收藏标签',requested:20,started_at:now,last_progress_at:now,heartbeat_at:now};return response(xhsTask)}if(url==='/api/xhs/sync/cancel'&&options.method==='POST'){xhsTask={...xhsTask,status:'cancelled',phase:'cancelled',message:'任务已取消',finished_at:new Date().toISOString()};return response(xhsTask)}if(url==='/api/xhs/sync/status')return response(xhsTask);if(url==='/api/inbox/items'&&options.method==='DELETE')return response({...inbox,version:'v2',raw_content:'',pending_item_count:0,pending_url_count:0,items:[]});if(url==='/api/inbox')return response(inboxData);if(url==='/api/processor/start'){taskStatus={...idle,task_id:'t',status:'processing'};setTimeout(()=>taskStatus={...taskStatus,status:'success',processed:1,success:1},50);return response(taskStatus)}if(url==='/api/processor/status')return response(taskStatus);if(url==='/api/notion/recent')return response({items:[{item_id:'1',title:'文章',original_url:'https://source',normalized_url:'https://source/',notion_url:'https://notion/page',created_at:'2026-01-01T00:00:00Z',status:'archived'}]});if(url==='/api/hot')return response({content:'# 项目记忆\n\n<script>bad()</script>'});return response({})}))})
afterEach(()=>{cleanup();vi.unstubAllGlobals();Object.assign(session,{loggedIn:false,status:'idle'});window.history.pushState({},'', '/')})
describe('Knowledge Console',()=>{
it('renders every dashboard region and a memory entry button',async()=>{render(<App/>);expect(await screen.findByRole('heading',{name:/Knowledge Console/})).toBeInTheDocument();for(const title of ['小红书授权','读取收藏','Notion 数据库配置','项目记忆','待整理收件箱','自动整理任务','最近 Notion 整理结果'])expect(screen.getByText(title)).toBeInTheDocument();expect(screen.getByRole('link',{name:'打开 hot.md'})).toHaveAttribute('href','/console/memory');expect(await screen.findByText('文章')).toBeInTheDocument()})
it('offers Chrome login without a cookie field',async()=>{render(<App/>);expect(await screen.findByRole('link',{name:'连接 Chrome'})).toHaveAttribute('href','/console/login/xiaohongshu');expect(screen.queryByLabelText('Cookie')).toBeNull()})
it('starts and polls a background job',async()=>{render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'开始整理'}));await waitFor(()=>expect(requests.some(x=>x.url==='/api/processor/start')).toBe(true));await waitFor(()=>expect(screen.getAllByText('成功').some(node=>node.classList.contains('badge'))).toBe(true),{timeout:2500})})
it('selects all inbox items and deletes them in one request',async()=>{const user=userEvent.setup();render(<App/>);await user.click(await screen.findByRole('button',{name:'全选'}));expect(screen.getByText('已选择 1 条')).toBeInTheDocument();expect(screen.getByRole('checkbox')).toBeChecked();await user.click(screen.getByRole('button',{name:'删除选中'}));await waitFor(()=>expect(requests.some(x=>x.url==='/api/inbox/items'&&x.options.method==='DELETE')).toBe(true));const request=requests.find(x=>x.url==='/api/inbox/items'&&x.options.method==='DELETE');expect(JSON.parse(String(request?.options.body))).toEqual({item_ids:['i'],version:'v'});expect(await screen.findByText('队列为空')).toBeInTheDocument()})
it('loads the server-side session without exposing cookies',async()=>{render(<App/>);await waitFor(()=>expect(requests.some(x=>x.url==='/api/xhs/session')).toBe(true));expect(document.body.textContent).not.toContain('private-cookie')})
it('submits the selected favorite limit from the dashboard left column',async()=>{Object.assign(session,{loggedIn:true,status:'authenticated'});const user=userEvent.setup();render(<App/>);const input=await screen.findByLabelText('本次读取数量（1–100）');await user.clear(input);await user.type(input,'35');await user.click(screen.getByRole('button',{name:'开始读取收藏'}));await waitFor(()=>expect(requests.some(x=>x.url==='/api/xhs/sync')).toBe(true));const request=requests.find(x=>x.url==='/api/xhs/sync');expect(JSON.parse(String(request?.options.body))).toEqual({limit:35})})
it('shows explicit Xiaohongshu step, heartbeat, progress and cancellation',async()=>{Object.assign(session,{loggedIn:true,status:'authenticated'});const user=userEvent.setup();render(<App/>);await user.click(await screen.findByRole('button',{name:'开始读取收藏'}));expect((await screen.findAllByText('打开收藏标签')).length).toBeGreaterThan(0);expect(screen.getByRole('progressbar',{name:'收藏任务进度'})).toBeInTheDocument();expect(screen.getByText('● 后台在线')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'取消任务'}));expect((await screen.findAllByText('任务已取消')).length).toBeGreaterThan(0);expect(requests.some(x=>x.url==='/api/xhs/sync/cancel')).toBe(true)})
it('opens hot.md on a dedicated safe page',async()=>{window.history.pushState({},'', '/console/memory');render(<App/>);expect(await screen.findByRole('heading',{name:'hot.md / 项目记忆',level:1})).toBeInTheDocument();expect(await screen.findByText('项目记忆')).toBeInTheDocument();expect(document.querySelector('script')).toBeNull()})
})
it('enables processing for a plain-text item without URLs',async()=>{
  inboxData={...inbox,raw_content:'纯文字内容',pending_item_count:1,pending_url_count:0,items:[{...inbox.items[0],content:'纯文字内容',urls:[]}]}
  render(<App/>)
  expect(await screen.findByRole('button',{name:'开始整理'})).toBeEnabled()
})
